import type { Tracer } from "../types";
import * as F from "./flagship";
import * as G from "./greedy";
import * as H from "./hashing";
import * as S from "./searching";
import * as T from "./twoPointers";
import * as W from "./windows";
import * as LF from "./ll/fastSlow";
import * as LH from "./ll/hashWalk";
import * as LM from "./ll/merge";
import * as LN from "./ll/numbers";
import * as LR from "./ll/rewiring";

export const TRACERS: Record<string, Tracer> = {
  "kadane-brute": F.kadaneBrute,
  "kadane-improved": F.kadaneImproved,
  "kadane-optimal": F.kadaneOptimal,
  "negatives-brute": F.negativesBrute,
  "negatives-improved": F.negativesImproved,
  "negatives-optimal": F.negativesOptimal,
  "pairs-brute": F.pairsBrute,
  "pairs-improved": F.pairsImproved,
  "pairs-optimal": F.pairsOptimal,
  reverse: T.reverseTracer,
  dnf012: T.dnf012Tracer,
  threeWay: T.threeWayTracer,
  alternating: T.alternatingTracer,
  mergeGap: T.mergeGapTracer,
  rotateOne: T.rotateOneTracer,
  palindromeOps: T.palindromeOpsTracer,
  trapping: T.trappingTracer,
  floyd: T.floydTracer,
  unionInter: T.unionInterTracer,
  common3: T.common3Tracer,
  triplet: T.tripletTracer,
  smallestSub: W.smallestSubTracer,
  maxProduct: W.maxProductTracer,
  minSwapsK: W.minSwapsKTracer,
  stockOnce: W.stockOnceTracer,
  zeroSum: H.zeroSumTracer,
  longestConsec: H.longestConsecTracer,
  nByK: H.nByKTracer,
  subset: H.subsetTracer,
  maxMin: S.maxMinTracer,
  quickselect: S.quickselectTracer,
  inversions: S.inversionsTracer,
  median: S.medianTracer,
  chocolate: S.chocolateTracer,
  heights: G.heightsTracer,
  jumps: G.jumpsTracer,
  intervals: G.intervalsTracer,
  nextPerm: G.nextPermTracer,
  profitTwice: G.profitTwiceTracer,
  factorial: G.factorialTracer,

  // linked lists
  "ll-reverse-stack": LR.llReverseStack,
  "ll-reverse-recursive": LR.llReverseRecursive,
  "ll-reverse": LR.llReverseIterative,
  "ll-reverse-k": LR.llReverseK,
  "ll-move-last": LR.llMoveLast,
  "ll-circular-delete": LR.llCircularDelete,
  "ll-reverse-dll": LR.llReverseDLL,
  "ll-rotate-dll": LR.llRotateDLL,
  "ll-reverse-dll-groups": LR.llReverseDLLGroups,
  "ll-reverse-flag": LR.llReverseFlag,
  "ll-delete-greater-right": LR.llDeleteGreaterRight,
  "ll-sort-012": LR.llSort012,
  "ll-even-odd": LR.llEvenOdd,
  "ll-dedup-sorted": LR.llDedupSorted,
  "ll-loop-hash": LF.llLoopHash,
  "ll-loop-mark": LF.llLoopMark,
  "ll-loop-floyd": LF.llLoopFloyd,
  "ll-loop-start": LF.llLoopStart,
  "ll-remove-loop": LF.llRemoveLoop,
  "ll-middle": LF.llMiddle,
  "ll-is-circular": LF.llIsCircular,
  "ll-split-circular": LF.llSplitCircular,
  "ll-palindrome": LF.llPalindrome,
  "ll-nth-from-end": LF.llNthFromEnd,
  "ll-intersect-sorted": LM.llIntersectSorted,
  "ll-sort-array": LM.llSortArray,
  "ll-insertion-sort": LM.llInsertionSort,
  "ll-merge-sort": LM.llMergeSort,
  "ll-quick-sort": LM.llQuickSort,
  "ll-k-sorted": LM.llKSorted,
  "ll-flatten": LM.llFlatten,
  "ll-merge-k": LM.llMergeK,
  "ll-add-one": LN.llAddOne,
  "ll-add-two": LN.llAddTwo,
  "ll-multiply": LN.llMultiply,
  "ll-dedup-nested": LH.llDedupNested,
  "ll-dedup-hash": LH.llDedupHash,
  "ll-intersection-point": LH.llIntersectionPoint,
  "ll-pairs-dll": LH.llPairsDLL,
  "ll-triplets-dll": LH.llTripletsDLL,
  "ll-clone-random": LH.llCloneRandom,
  "ll-first-unique": LH.llFirstUnique,
};
